---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: GET_TemplatesDeploymentprofiles
    inherits: 
    description: 
  fields:
  - execute:
      value: get_templates_deploymentprofiles
