---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: POST_AdminConfigfiles
    inherits: 
    description: 
  fields:
  - method:
      value: post
  - execute:
      value: post_admin_configfiles
