---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: PUT_SettingsNotifications
    inherits: 
    description: 
  fields:
  - method:
      value: put
  - execute:
      value: put_settings_notifications
