---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: DELETE_GroupsApplications
    inherits: 
    description: 
  fields:
  - execute:
      value: delete_groups_applications
