---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: POST_GroupsApplicationsResourcesActionpermit
    inherits: 
    description: 
  fields:
  - execute:
      value: post_groups_applications_resources_actionpermit
