---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: POST_ApplicationsVirtualmachinesApplicationsResourcesActionpermit
    inherits: 
    description: 
  fields:
  - execute:
      value: post_applications_virtualmachines_applications_resources_actionpermit
