---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: CatalogItemInitialization_Application
    inherits: 
    description: 
  fields:
  - sequencer:
      value: "/Service/Provisioning/StateMachines/Methods/GroupSequenceCheck"
  - pre1:
      value: "/Service/Provisioning/StateMachines/Methods/DialogParser"
  - pre2:
      value: "/Service/Provisioning/StateMachines/Methods/CatalogItemInitialization_Application"
  - provision:
      value: "/Service/Provisioning/StateMachines/Methods/ProvisionGeneric"
  - checkprovisioned:
      value: "/Service/Provisioning/StateMachines/Methods/ProvisionGeneric"
