---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: Provision VM from Template
    name: template
    inherits: 
    description: 
  fields:
  - VMname:
      value: "/Infrastructure/VM/Provisioning/Naming/ModifyName"
  - Provision:
      value: "/Infrastructure/VM/Provisioning/StateMachines/Methods/Provision"
  - CheckProvisioned:
      value: "/Infrastructure/VM/Provisioning/StateMachines/Methods/CheckProvisioned"
  - Networking:
      value: "/CustomMethods/BackupNetwork/BackupNetwork/BackupNic"
  - ConfigureDisk:
      value: "/CustomMethods/AddDisk/AddSecondDisk/AddDisk"
