---
object_type: method
version: 1.0
object:
  attributes:
    name: modify_vmname
    display_name: modify_default
    description: 
    scope: instance
    language: ruby
    location: inline
    options: {}
  inputs: []
