---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: default
    inherits: 
    description: ModifyName
  fields:
  - vm_prefix:
      value: hou
  - meth1:
      value: vmname
